---
title: "pretzel"
output: html_document
date: "2024-02-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(42)
```

```{r}
library(readxl)
library(writexl)
library(mice)
library(fastDummies)

library(missMDA)
library(FactoMineR)
library(factoextra)
library(nFactors)

library(TDAstats)
library(TDApplied)
library(TDA)
library(missForest)

library(ggplot2)
library(ggpubr)
library(ggforce)

library(dplyr)
library(plotrix)
```

# pretzel
```{r}
# t <- seq(-2.4, 2.4, length.out = 100)
t <- runif(150, -2.4, 2.4)
a <- 2
x <- a * (-t^4 + 4 * t^2 - 3) / (2 * t^2 + 2) + rnorm(100) * 0.1
y <- a * (t^3 - 3 * t) / (t^2 + 1) + rnorm(100) * 0.1

tst <- cbind(x, y)

rot <- matrix(c(0, 1, -1, 0), ncol=2, nrow = 2)

tst <- tst %*% rot

pretzel <- data.frame(tst)
colnames(pretzel) <- c("x", "y")
pretzel
```

```{r}
RipsFilt <- ripsFiltration(pretzel, maxdimension = 1, maxscale = 50,
                       dist = "euclidean")
```

```{r}
plot_fun <- function(filt, r) {
    data <- filt$coordinates
    xlims = c(-2.5, 2.5)
    ylims = c(-1, 3.5)
      plot(NULL, type = "n", xlim = xlims, ylim = ylims, main = NULL,
                xlab = "", ylab = "", asp = 1, axes = FALSE) 
      for(j in 1:length(data[, 1])) {
        draw.circle(x = data[j, 1], y = data[j, 2], radius = r / 2,
        col = rgb(144/255, 238/255, 144/255, 0.035))
      }
      for (idx in seq(along = filt[["cmplx"]][filt$values < r])) {
        polygon(data[filt[["cmplx"]][[idx]], 1], data[filt[["cmplx"]][[idx]], 2],
                col = rgb(153, 37, 190, 10, maxColorValue = 255), lwd = .1)
      }
      for (idx in seq(along = filt[["cmplx"]][filt$values < r])) {
        polygon(data[filt[["cmplx"]][[idx]], 1], data[filt[["cmplx"]][[idx]], 2],
                col = NULL, border = rgb(72, 10, 92, 100, maxColorValue = 255), lwd = .2)
      }
      points(data[,1], data[,2], pch = 16, cex=.5)
 }
```

```{r}
png(file = "img/pretzel_rips_0.png")
plot_fun(RipsFilt, 0)
dev.off()
```

```{r}
png(file = "img/pretzel_rips_1.png")
plot_fun(RipsFilt, 0.4)
dev.off()
```

```{r}
png(file = "img/pretzel_rips_2.png")
plot_fun(RipsFilt, 1.04)
dev.off()
```

```{r}
png(file = "img/pretzel_rips_3.png")
plot_fun(RipsFilt, 1.3)
dev.off()
```

```{r}
png(file = "img/pretzel_rips_4.png")
plot_fun(RipsFilt, 1.5)
dev.off()
```

```{r}
png(file = "img/pretzel_rips_5.png")
plot_fun(RipsFilt, 2.4)
dev.off()
```

```{r}
pretzel_hom <- calculate_homology(pretzel)
```

```{r}
pretzel_hom[pretzel_hom[, "dimension"] == 1, ]
```
```{r}
p <- ggplot2::ggplot(data = data.frame(pretzel_hom[pretzel_hom[, "dimension"] == 1, ])) +
    ggplot2::xlim(0, 2.5) +
    ggplot2::ylim(0, 2.5) +
    ggplot2::geom_abline(slope = 1, intercept = 0) +
    ggplot2::xlab("Birth") +
    ggplot2::ylab("Death") +
    ggplot2::theme(axis.line = ggplot2::element_line(colour = "black"),
                   panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
                   panel.background = ggplot2::element_blank()) +
    ggplot2::geom_point(ggplot2::aes_string(x = "birth",
                                            y = "death"), shape = 17, colour = "#00BFC4", size=3.5) +
    ggplot2::coord_fixed(ratio = 1) 
    #ggtitle("") +
    #theme(plot.title = element_text(color = "black", hjust = title_hjust, vjust = title_vjust, size=title_size))

  p
```

```{r}
png(file = "img/pretzel_dg.png")
#plot_persist(pretzel_hom[pretzel_hom[, "dimension"] == 1, ], )
p
dev.off()
```







